CREATE TABLE IF NOT EXISTS pessoa (
    id_pessoa BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    data_nascimento DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS conta (
    id_conta BIGINT PRIMARY KEY AUTO_INCREMENT,
    id_pessoa BIGINT NOT NULL,
    saldo DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    limite_saque_diario DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    flag_ativo BOOLEAN NOT NULL DEFAULT TRUE,
    tipo_conta BIGINT NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transacao (
    id_transacao BIGINT PRIMARY KEY AUTO_INCREMENT,
    id_conta BIGINT NOT NULL,
    valor DECIMAL(15,2) NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_conta) REFERENCES conta(id_conta) ON DELETE CASCADE
);